#!/bin/sh

. /etc/rc.subr

name=specter_dns
rcvar=${name}_enable
pidfile=/var/run/${name}.pid
command=/usr/sbin/daemon
command_args="-P ${pidfile} /usr/local/libexec/specter/dns-launch"
required_files="/usr/local/etc/specter/dns.env"

load_rc_config $name
: ${specter_dns_enable:=NO}

run_rc_command "$1"
