// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: kv/aof/proto/mutation.proto

package proto

import (
	protocol "go.miragespace.co/specter/spec/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutationType int32

const (
	MutationType_UNKNOWN_TYPE  MutationType = 0
	MutationType_SIMPLE_PUT    MutationType = 1
	MutationType_SIMPLE_DELETE MutationType = 3
	MutationType_PREFIX_APPEND MutationType = 5
	MutationType_PREFIX_REMOVE MutationType = 7
	MutationType_IMPORT        MutationType = 20
	MutationType_REMOVE_KEYS   MutationType = 21
)

// Enum value maps for MutationType.
var (
	MutationType_name = map[int32]string{
		0:  "UNKNOWN_TYPE",
		1:  "SIMPLE_PUT",
		3:  "SIMPLE_DELETE",
		5:  "PREFIX_APPEND",
		7:  "PREFIX_REMOVE",
		20: "IMPORT",
		21: "REMOVE_KEYS",
	}
	MutationType_value = map[string]int32{
		"UNKNOWN_TYPE":  0,
		"SIMPLE_PUT":    1,
		"SIMPLE_DELETE": 3,
		"PREFIX_APPEND": 5,
		"PREFIX_REMOVE": 7,
		"IMPORT":        20,
		"REMOVE_KEYS":   21,
	}
)

func (x MutationType) Enum() *MutationType {
	p := new(MutationType)
	*p = x
	return p
}

func (x MutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_aof_proto_mutation_proto_enumTypes[0].Descriptor()
}

func (MutationType) Type() protoreflect.EnumType {
	return &file_kv_aof_proto_mutation_proto_enumTypes[0]
}

func (x MutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationType.Descriptor instead.
func (MutationType) EnumDescriptor() ([]byte, []int) {
	return file_kv_aof_proto_mutation_proto_rawDescGZIP(), []int{0}
}

type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MutationType           `protobuf:"varint,1,opt,name=type,proto3,enum=proto.MutationType" json:"type,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,10,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        []*protocol.KVTransfer `protobuf:"bytes,20,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_kv_aof_proto_mutation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_kv_aof_proto_mutation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_kv_aof_proto_mutation_proto_rawDescGZIP(), []int{0}
}

func (x *Mutation) GetType() MutationType {
	if x != nil {
		return x.Type
	}
	return MutationType_UNKNOWN_TYPE
}

func (x *Mutation) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Mutation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Mutation) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Mutation) GetValues() []*protocol.KVTransfer {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_kv_aof_proto_mutation_proto protoreflect.FileDescriptor

const file_kv_aof_proto_mutation_proto_rawDesc = "" +
	"\n" +
	"\x1bkv/aof/proto/mutation.proto\x12\x05proto\x1a\x13spec/proto/kv.proto\"\x9d\x01\n" +
	"\bMutation\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.proto.MutationTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x12\n" +
	"\x04keys\x18\n" +
	" \x03(\fR\x04keys\x12,\n" +
	"\x06values\x18\x14 \x03(\v2\x14.protocol.KVTransferR\x06values*\x86\x01\n" +
	"\fMutationType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\x0e\n" +
	"\n" +
	"SIMPLE_PUT\x10\x01\x12\x11\n" +
	"\rSIMPLE_DELETE\x10\x03\x12\x11\n" +
	"\rPREFIX_APPEND\x10\x05\x12\x11\n" +
	"\rPREFIX_REMOVE\x10\a\x12\n" +
	"\n" +
	"\x06IMPORT\x10\x14\x12\x0f\n" +
	"\vREMOVE_KEYS\x10\x15B*H\x01Z&go.miragespace.co/specter/kv/aof/protob\x06proto3"

var (
	file_kv_aof_proto_mutation_proto_rawDescOnce sync.Once
	file_kv_aof_proto_mutation_proto_rawDescData []byte
)

func file_kv_aof_proto_mutation_proto_rawDescGZIP() []byte {
	file_kv_aof_proto_mutation_proto_rawDescOnce.Do(func() {
		file_kv_aof_proto_mutation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_aof_proto_mutation_proto_rawDesc), len(file_kv_aof_proto_mutation_proto_rawDesc)))
	})
	return file_kv_aof_proto_mutation_proto_rawDescData
}

var file_kv_aof_proto_mutation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kv_aof_proto_mutation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kv_aof_proto_mutation_proto_goTypes = []any{
	(MutationType)(0),           // 0: proto.MutationType
	(*Mutation)(nil),            // 1: proto.Mutation
	(*protocol.KVTransfer)(nil), // 2: protocol.KVTransfer
}
var file_kv_aof_proto_mutation_proto_depIdxs = []int32{
	0, // 0: proto.Mutation.type:type_name -> proto.MutationType
	2, // 1: proto.Mutation.values:type_name -> protocol.KVTransfer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kv_aof_proto_mutation_proto_init() }
func file_kv_aof_proto_mutation_proto_init() {
	if File_kv_aof_proto_mutation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_aof_proto_mutation_proto_rawDesc), len(file_kv_aof_proto_mutation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kv_aof_proto_mutation_proto_goTypes,
		DependencyIndexes: file_kv_aof_proto_mutation_proto_depIdxs,
		EnumInfos:         file_kv_aof_proto_mutation_proto_enumTypes,
		MessageInfos:      file_kv_aof_proto_mutation_proto_msgTypes,
	}.Build()
	File_kv_aof_proto_mutation_proto = out.File
	file_kv_aof_proto_mutation_proto_goTypes = nil
	file_kv_aof_proto_mutation_proto_depIdxs = nil
}
