version: '3.9`'

services:
  nginx:
    image: nginxdemos/hello
    restart: unless-stopped
    networks:
      - specter

  client:
    image: specter
    restart: unless-stopped
    depends_on:
      - nginx
    networks:
      - specter
    environment:
      - DOH=false
    volumes:
      - ./dev/client:/app/config
    command: --verbose client --insecure tunnel --config /app/config/specter.yaml

networks:
  specter: