# syntax = docker/dockerfile:1-experimental

FROM --platform=$BUILDPLATFORM golang:1.19-bullseye as builder
RUN apt install ca-certificates gcc
WORKDIR /app
COPY . .

RUN cat /etc/ssl/certs/ca-certificates.crt /app/dev/pebble/certs/cert.pem > /app/ca-certificates.crt

ARG TARGETOS
ARG TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    GOOS=$TARGETOS GOARCH=$TARGETARCH GOARM=7 GOAMD64=v3 \
    go build -race -tags 'osusergo netgo urfave_cli_no_docs no_mocks' \
    -ldflags "-s -w -extldflags -static -X 'kon.nect.sh/specter/spec/cipher.CertCA=https://pebble:14000/dir' -X 'kon.nect.sh/specter/cmd/client.devApexOverride=dev.con.nect.sh'" \
    -o bin/specter .

FROM --platform=$BUILDPLATFORM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/bin/specter /app/specter

ENTRYPOINT ["/app/specter"]