version: '3'

services:
  seed:
    image: specter
    restart: unless-stopped
    ports:
      - "1112:1112"
      - "1113:1113"
    volumes:
      - ./certs:/certs
    command: --debug server --cert-dir /certs --chord seed:1111 --client seed:1112 --gateway seed:1113 -z example.com

  node-a:
    image: specter
    restart: unless-stopped
    ports:
      - "2112:1112"
      - "2113:1113"
    volumes:
      - ./certs:/certs
    command: --debug server --cert-dir /certs --join seed:1111 --chord node-a:1111 --client node-a:1112 --gateway node-a:1113 -z example.com

  node-b:
    image: specter
    restart: unless-stopped
    ports:
      - "3112:1112"
      - "3113:1113"
    volumes:
      - ./certs:/certs
    command: --debug server --cert-dir /certs --join seed:1111 --chord node-b:1111 --client node-b:1112 --gateway node-b:1113 -z example.com

  node-c:
    image: specter
    restart: unless-stopped
    ports:
      - "4112:1112"
      - "4113:1113"
    volumes:
      - ./certs:/certs
    command: --debug server --cert-dir /certs --join seed:1111 --chord node-c:1111 --client node-c:1112 --gateway node-c:1113 -z example.com

  node-d:
    image: specter
    restart: unless-stopped
    ports:
      - "5112:1112"
      - "5113:1113"
    volumes:
      - ./certs:/certs
    command: --debug server --cert-dir /certs --join seed:1111 --chord node-d:1111 --client node-d:1112 --gateway node-d:1113 -z example.com