# fly.toml app configuration file generated for specter on 2023-08-03T11:22:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "specter"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "3m0s"

[build]
  dockerfile = "Dockerfile.flyio"

[env]
  GOMEMLIMIT = "200MiB"

[[mounts]]
  source = "kv"
  destination = "/data/kv"
  processes = ["app"]

[[services]]
  protocol = "udp"
  internal_port = 443

  [[services.ports]]
    port = 443

[[services]]
  protocol = "tcp"
  internal_port = 443

  [[services.ports]]
    port = 443
    handlers = ["proxy_proto"]

[[services]]
  protocol = "udp"
  internal_port = 53

  [[services.ports]]
    port = 53

[[services]]
  protocol = "tcp"
  internal_port = 53

  [[services.ports]]
    port = 53

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 80
    handlers = ["proxy_proto"]
