// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: spec/proto/pki.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *ProofOfWork           `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_spec_proto_pki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_pki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_pki_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateRequest) GetProof() *ProofOfWork {
	if x != nil {
		return x.Proof
	}
	return nil
}

type CertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertDer       []byte                 `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	CertPem       []byte                 `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_spec_proto_pki_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_pki_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_pki_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *CertificateResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

var File_spec_proto_pki_proto protoreflect.FileDescriptor

const file_spec_proto_pki_proto_rawDesc = "" +
	"\n" +
	"\x14spec/proto/pki.proto\x12\bprotocol\x1a\x14spec/proto/pow.proto\"A\n" +
	"\x12CertificateRequest\x12+\n" +
	"\x05proof\x18\x01 \x01(\v2\x15.protocol.ProofOfWorkR\x05proof\"K\n" +
	"\x13CertificateResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\fR\acertPem2_\n" +
	"\n" +
	"PKIService\x12Q\n" +
	"\x12RequestCertificate\x12\x1c.protocol.CertificateRequest\x1a\x1d.protocol.CertificateResponseB+H\x01Z'go.miragespace.co/specter/spec/protocolb\x06proto3"

var (
	file_spec_proto_pki_proto_rawDescOnce sync.Once
	file_spec_proto_pki_proto_rawDescData []byte
)

func file_spec_proto_pki_proto_rawDescGZIP() []byte {
	file_spec_proto_pki_proto_rawDescOnce.Do(func() {
		file_spec_proto_pki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_proto_pki_proto_rawDesc), len(file_spec_proto_pki_proto_rawDesc)))
	})
	return file_spec_proto_pki_proto_rawDescData
}

var file_spec_proto_pki_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spec_proto_pki_proto_goTypes = []any{
	(*CertificateRequest)(nil),  // 0: protocol.CertificateRequest
	(*CertificateResponse)(nil), // 1: protocol.CertificateResponse
	(*ProofOfWork)(nil),         // 2: protocol.ProofOfWork
}
var file_spec_proto_pki_proto_depIdxs = []int32{
	2, // 0: protocol.CertificateRequest.proof:type_name -> protocol.ProofOfWork
	0, // 1: protocol.PKIService.RequestCertificate:input_type -> protocol.CertificateRequest
	1, // 2: protocol.PKIService.RequestCertificate:output_type -> protocol.CertificateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spec_proto_pki_proto_init() }
func file_spec_proto_pki_proto_init() {
	if File_spec_proto_pki_proto != nil {
		return
	}
	file_spec_proto_pow_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_proto_pki_proto_rawDesc), len(file_spec_proto_pki_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_proto_pki_proto_goTypes,
		DependencyIndexes: file_spec_proto_pki_proto_depIdxs,
		MessageInfos:      file_spec_proto_pki_proto_msgTypes,
	}.Build()
	File_spec_proto_pki_proto = out.File
	file_spec_proto_pki_proto_goTypes = nil
	file_spec_proto_pki_proto_depIdxs = nil
}
