// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: spec/proto/pow.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProofOfWork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        []byte                 `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Solution      string                 `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofOfWork) Reset() {
	*x = ProofOfWork{}
	mi := &file_spec_proto_pow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofOfWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofOfWork) ProtoMessage() {}

func (x *ProofOfWork) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_pow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofOfWork.ProtoReflect.Descriptor instead.
func (*ProofOfWork) Descriptor() ([]byte, []int) {
	return file_spec_proto_pow_proto_rawDescGZIP(), []int{0}
}

func (x *ProofOfWork) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *ProofOfWork) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ProofOfWork) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

var File_spec_proto_pow_proto protoreflect.FileDescriptor

var file_spec_proto_pow_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x77,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x22, 0x60, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x4f, 0x66, 0x57, 0x6f, 0x72, 0x6b, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x2b, 0x48, 0x01, 0x5a, 0x27, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x72, 0x61, 0x67,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x72, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_spec_proto_pow_proto_rawDescOnce sync.Once
	file_spec_proto_pow_proto_rawDescData []byte
)

func file_spec_proto_pow_proto_rawDescGZIP() []byte {
	file_spec_proto_pow_proto_rawDescOnce.Do(func() {
		file_spec_proto_pow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_proto_pow_proto_rawDesc), len(file_spec_proto_pow_proto_rawDesc)))
	})
	return file_spec_proto_pow_proto_rawDescData
}

var file_spec_proto_pow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spec_proto_pow_proto_goTypes = []any{
	(*ProofOfWork)(nil), // 0: protocol.ProofOfWork
}
var file_spec_proto_pow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spec_proto_pow_proto_init() }
func file_spec_proto_pow_proto_init() {
	if File_spec_proto_pow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_proto_pow_proto_rawDesc), len(file_spec_proto_pow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_proto_pow_proto_goTypes,
		DependencyIndexes: file_spec_proto_pow_proto_depIdxs,
		MessageInfos:      file_spec_proto_pow_proto_msgTypes,
	}.Build()
	File_spec_proto_pow_proto = out.File
	file_spec_proto_pow_proto_goTypes = nil
	file_spec_proto_pow_proto_depIdxs = nil
}
