// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: spec/proto/rpc.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context_TargetType int32

const (
	Context_UNKNOWN          Context_TargetType = 0
	Context_KV_REPLICATION   Context_TargetType = 1
	Context_KV_DIRECT_TARGET Context_TargetType = 2
)

// Enum value maps for Context_TargetType.
var (
	Context_TargetType_name = map[int32]string{
		0: "UNKNOWN",
		1: "KV_REPLICATION",
		2: "KV_DIRECT_TARGET",
	}
	Context_TargetType_value = map[string]int32{
		"UNKNOWN":          0,
		"KV_REPLICATION":   1,
		"KV_DIRECT_TARGET": 2,
	}
)

func (x Context_TargetType) Enum() *Context_TargetType {
	p := new(Context_TargetType)
	*p = x
	return p
}

func (x Context_TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Context_TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_proto_rpc_proto_enumTypes[0].Descriptor()
}

func (Context_TargetType) Type() protoreflect.EnumType {
	return &file_spec_proto_rpc_proto_enumTypes[0]
}

func (x Context_TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Context_TargetType.Descriptor instead.
func (Context_TargetType) EnumDescriptor() ([]byte, []int) {
	return file_spec_proto_rpc_proto_rawDescGZIP(), []int{0, 0}
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestTarget Context_TargetType     `protobuf:"varint,1,opt,name=requestTarget,proto3,enum=protocol.Context_TargetType" json:"requestTarget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_spec_proto_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_spec_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetRequestTarget() Context_TargetType {
	if x != nil {
		return x.RequestTarget
	}
	return Context_UNKNOWN
}

var File_spec_proto_rpc_proto protoreflect.FileDescriptor

const file_spec_proto_rpc_proto_rawDesc = "" +
	"\n" +
	"\x14spec/proto/rpc.proto\x12\bprotocol\"\x92\x01\n" +
	"\aContext\x12B\n" +
	"\rrequestTarget\x18\x01 \x01(\x0e2\x1c.protocol.Context.TargetTypeR\rrequestTarget\"C\n" +
	"\n" +
	"TargetType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eKV_REPLICATION\x10\x01\x12\x14\n" +
	"\x10KV_DIRECT_TARGET\x10\x02B+H\x01Z'go.miragespace.co/specter/spec/protocolb\x06proto3"

var (
	file_spec_proto_rpc_proto_rawDescOnce sync.Once
	file_spec_proto_rpc_proto_rawDescData []byte
)

func file_spec_proto_rpc_proto_rawDescGZIP() []byte {
	file_spec_proto_rpc_proto_rawDescOnce.Do(func() {
		file_spec_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_proto_rpc_proto_rawDesc), len(file_spec_proto_rpc_proto_rawDesc)))
	})
	return file_spec_proto_rpc_proto_rawDescData
}

var file_spec_proto_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spec_proto_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spec_proto_rpc_proto_goTypes = []any{
	(Context_TargetType)(0), // 0: protocol.Context.TargetType
	(*Context)(nil),         // 1: protocol.Context
}
var file_spec_proto_rpc_proto_depIdxs = []int32{
	0, // 0: protocol.Context.requestTarget:type_name -> protocol.Context.TargetType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spec_proto_rpc_proto_init() }
func file_spec_proto_rpc_proto_init() {
	if File_spec_proto_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_proto_rpc_proto_rawDesc), len(file_spec_proto_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_proto_rpc_proto_goTypes,
		DependencyIndexes: file_spec_proto_rpc_proto_depIdxs,
		EnumInfos:         file_spec_proto_rpc_proto_enumTypes,
		MessageInfos:      file_spec_proto_rpc_proto_msgTypes,
	}.Build()
	File_spec_proto_rpc_proto = out.File
	file_spec_proto_rpc_proto_goTypes = nil
	file_spec_proto_rpc_proto_depIdxs = nil
}
