// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: spec/proto/rpc.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context_TargetType int32

const (
	Context_UNKNOWN          Context_TargetType = 0
	Context_KV_REPLICATION   Context_TargetType = 1
	Context_KV_DIRECT_TARGET Context_TargetType = 2
)

// Enum value maps for Context_TargetType.
var (
	Context_TargetType_name = map[int32]string{
		0: "UNKNOWN",
		1: "KV_REPLICATION",
		2: "KV_DIRECT_TARGET",
	}
	Context_TargetType_value = map[string]int32{
		"UNKNOWN":          0,
		"KV_REPLICATION":   1,
		"KV_DIRECT_TARGET": 2,
	}
)

func (x Context_TargetType) Enum() *Context_TargetType {
	p := new(Context_TargetType)
	*p = x
	return p
}

func (x Context_TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Context_TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_proto_rpc_proto_enumTypes[0].Descriptor()
}

func (Context_TargetType) Type() protoreflect.EnumType {
	return &file_spec_proto_rpc_proto_enumTypes[0]
}

func (x Context_TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Context_TargetType.Descriptor instead.
func (Context_TargetType) EnumDescriptor() ([]byte, []int) {
	return file_spec_proto_rpc_proto_rawDescGZIP(), []int{0, 0}
}

type Context struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestTarget Context_TargetType `protobuf:"varint,1,opt,name=requestTarget,proto3,enum=protocol.Context_TargetType" json:"requestTarget,omitempty"`
}

func (x *Context) Reset() {
	*x = Context{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_spec_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetRequestTarget() Context_TargetType {
	if x != nil {
		return x.RequestTarget
	}
	return Context_UNKNOWN
}

var File_spec_proto_rpc_proto protoreflect.FileDescriptor

var file_spec_proto_rpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x22, 0x92, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x42, 0x0a, 0x0d,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x22, 0x43, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4b,
	0x56, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12,
	0x14, 0x0a, 0x10, 0x4b, 0x56, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x41, 0x52,
	0x47, 0x45, 0x54, 0x10, 0x02, 0x42, 0x2b, 0x48, 0x01, 0x5a, 0x27, 0x67, 0x6f, 0x2e, 0x6d, 0x69,
	0x72, 0x61, 0x67, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x2f, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spec_proto_rpc_proto_rawDescOnce sync.Once
	file_spec_proto_rpc_proto_rawDescData = file_spec_proto_rpc_proto_rawDesc
)

func file_spec_proto_rpc_proto_rawDescGZIP() []byte {
	file_spec_proto_rpc_proto_rawDescOnce.Do(func() {
		file_spec_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_proto_rpc_proto_rawDescData)
	})
	return file_spec_proto_rpc_proto_rawDescData
}

var file_spec_proto_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spec_proto_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spec_proto_rpc_proto_goTypes = []interface{}{
	(Context_TargetType)(0), // 0: protocol.Context.TargetType
	(*Context)(nil),         // 1: protocol.Context
}
var file_spec_proto_rpc_proto_depIdxs = []int32{
	0, // 0: protocol.Context.requestTarget:type_name -> protocol.Context.TargetType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spec_proto_rpc_proto_init() }
func file_spec_proto_rpc_proto_init() {
	if File_spec_proto_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spec_proto_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Context); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_proto_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_proto_rpc_proto_goTypes,
		DependencyIndexes: file_spec_proto_rpc_proto_depIdxs,
		EnumInfos:         file_spec_proto_rpc_proto_enumTypes,
		MessageInfos:      file_spec_proto_rpc_proto_msgTypes,
	}.Build()
	File_spec_proto_rpc_proto = out.File
	file_spec_proto_rpc_proto_rawDesc = nil
	file_spec_proto_rpc_proto_goTypes = nil
	file_spec_proto_rpc_proto_depIdxs = nil
}
