// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v4.22.2
// source: spec/proto/tunnel.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelStatusCode int32

const (
	TunnelStatusCode_STATUS_OK     TunnelStatusCode = 0
	TunnelStatusCode_UNKNOWN_ERROR TunnelStatusCode = 1
	TunnelStatusCode_NO_DIRECT     TunnelStatusCode = 2
)

// Enum value maps for TunnelStatusCode.
var (
	TunnelStatusCode_name = map[int32]string{
		0: "STATUS_OK",
		1: "UNKNOWN_ERROR",
		2: "NO_DIRECT",
	}
	TunnelStatusCode_value = map[string]int32{
		"STATUS_OK":     0,
		"UNKNOWN_ERROR": 1,
		"NO_DIRECT":     2,
	}
)

func (x TunnelStatusCode) Enum() *TunnelStatusCode {
	p := new(TunnelStatusCode)
	*p = x
	return p
}

func (x TunnelStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_proto_tunnel_proto_enumTypes[0].Descriptor()
}

func (TunnelStatusCode) Type() protoreflect.EnumType {
	return &file_spec_proto_tunnel_proto_enumTypes[0]
}

func (x TunnelStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelStatusCode.Descriptor instead.
func (TunnelStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

type Link_ALPN int32

const (
	Link_UNKNOWN        Link_ALPN = 0
	Link_SPECTER_CHORD  Link_ALPN = 1
	Link_SPECTER_CLIENT Link_ALPN = 2
	Link_HTTP2          Link_ALPN = 9
	Link_HTTP           Link_ALPN = 10
	Link_TCP            Link_ALPN = 11
)

// Enum value maps for Link_ALPN.
var (
	Link_ALPN_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "SPECTER_CHORD",
		2:  "SPECTER_CLIENT",
		9:  "HTTP2",
		10: "HTTP",
		11: "TCP",
	}
	Link_ALPN_value = map[string]int32{
		"UNKNOWN":        0,
		"SPECTER_CHORD":  1,
		"SPECTER_CLIENT": 2,
		"HTTP2":          9,
		"HTTP":           10,
		"TCP":            11,
	}
)

func (x Link_ALPN) Enum() *Link_ALPN {
	p := new(Link_ALPN)
	*p = x
	return p
}

func (x Link_ALPN) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Link_ALPN) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_proto_tunnel_proto_enumTypes[1].Descriptor()
}

func (Link_ALPN) Type() protoreflect.EnumType {
	return &file_spec_proto_tunnel_proto_enumTypes[1]
}

func (x Link_ALPN) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Link_ALPN.Descriptor instead.
func (Link_ALPN) EnumDescriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{0, 0}
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alpn     Link_ALPN `protobuf:"varint,1,opt,name=alpn,proto3,enum=protocol.Link_ALPN" json:"alpn,omitempty"`
	Hostname string    `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Remote   string    `protobuf:"bytes,3,opt,name=remote,proto3" json:"remote,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetAlpn() Link_ALPN {
	if x != nil {
		return x.Alpn
	}
	return Link_UNKNOWN
}

func (x *Link) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Link) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

type TunnelRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientDestination *Node  `protobuf:"bytes,1,opt,name=client_destination,json=clientDestination,proto3" json:"client_destination,omitempty"`
	ChordDestination  *Node  `protobuf:"bytes,2,opt,name=chord_destination,json=chordDestination,proto3" json:"chord_destination,omitempty"`
	TunnelDestination *Node  `protobuf:"bytes,3,opt,name=tunnel_destination,json=tunnelDestination,proto3" json:"tunnel_destination,omitempty"`
	Hostname          string `protobuf:"bytes,10,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *TunnelRoute) Reset() {
	*x = TunnelRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRoute) ProtoMessage() {}

func (x *TunnelRoute) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRoute.ProtoReflect.Descriptor instead.
func (*TunnelRoute) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelRoute) GetClientDestination() *Node {
	if x != nil {
		return x.ClientDestination
	}
	return nil
}

func (x *TunnelRoute) GetChordDestination() *Node {
	if x != nil {
		return x.ChordDestination
	}
	return nil
}

func (x *TunnelRoute) GetTunnelDestination() *Node {
	if x != nil {
		return x.TunnelDestination
	}
	return nil
}

func (x *TunnelRoute) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ClientToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ClientToken) Reset() {
	*x = ClientToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToken) ProtoMessage() {}

func (x *ClientToken) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToken.ProtoReflect.Descriptor instead.
func (*ClientToken) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *ClientToken) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ClientPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientPingRequest) Reset() {
	*x = ClientPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPingRequest) ProtoMessage() {}

func (x *ClientPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPingRequest.ProtoReflect.Descriptor instead.
func (*ClientPingRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

type ClientPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Apex string `protobuf:"bytes,2,opt,name=apex,proto3" json:"apex,omitempty"`
}

func (x *ClientPingResponse) Reset() {
	*x = ClientPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPingResponse) ProtoMessage() {}

func (x *ClientPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPingResponse.ProtoReflect.Descriptor instead.
func (*ClientPingResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *ClientPingResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ClientPingResponse) GetApex() string {
	if x != nil {
		return x.Apex
	}
	return ""
}

type RegisterIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterIdentityRequest) Reset() {
	*x = RegisterIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIdentityRequest) ProtoMessage() {}

func (x *RegisterIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIdentityRequest.ProtoReflect.Descriptor instead.
func (*RegisterIdentityRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

type RegisterIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apex string `protobuf:"bytes,2,opt,name=apex,proto3" json:"apex,omitempty"`
}

func (x *RegisterIdentityResponse) Reset() {
	*x = RegisterIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIdentityResponse) ProtoMessage() {}

func (x *RegisterIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIdentityResponse.ProtoReflect.Descriptor instead.
func (*RegisterIdentityResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterIdentityResponse) GetApex() string {
	if x != nil {
		return x.Apex
	}
	return ""
}

type GetNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{7}
}

type GetNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *GetNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GenerateHostnameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateHostnameRequest) Reset() {
	*x = GenerateHostnameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateHostnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHostnameRequest) ProtoMessage() {}

func (x *GenerateHostnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHostnameRequest.ProtoReflect.Descriptor instead.
func (*GenerateHostnameRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{9}
}

type GenerateHostnameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *GenerateHostnameResponse) Reset() {
	*x = GenerateHostnameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateHostnameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHostnameResponse) ProtoMessage() {}

func (x *GenerateHostnameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHostnameResponse.ProtoReflect.Descriptor instead.
func (*GenerateHostnameResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateHostnameResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisteredHostnamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisteredHostnamesRequest) Reset() {
	*x = RegisteredHostnamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredHostnamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredHostnamesRequest) ProtoMessage() {}

func (x *RegisteredHostnamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredHostnamesRequest.ProtoReflect.Descriptor instead.
func (*RegisteredHostnamesRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{11}
}

type RegisteredHostnamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostnames []string `protobuf:"bytes,1,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
}

func (x *RegisteredHostnamesResponse) Reset() {
	*x = RegisteredHostnamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredHostnamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredHostnamesResponse) ProtoMessage() {}

func (x *RegisteredHostnamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredHostnamesResponse.ProtoReflect.Descriptor instead.
func (*RegisteredHostnamesResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{12}
}

func (x *RegisteredHostnamesResponse) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

type PublishTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// servers are tun identities
	Servers []*Node `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *PublishTunnelRequest) Reset() {
	*x = PublishTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTunnelRequest) ProtoMessage() {}

func (x *PublishTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTunnelRequest.ProtoReflect.Descriptor instead.
func (*PublishTunnelRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *PublishTunnelRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PublishTunnelRequest) GetServers() []*Node {
	if x != nil {
		return x.Servers
	}
	return nil
}

type PublishTunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Published []*Node `protobuf:"bytes,1,rep,name=published,proto3" json:"published,omitempty"`
}

func (x *PublishTunnelResponse) Reset() {
	*x = PublishTunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTunnelResponse) ProtoMessage() {}

func (x *PublishTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTunnelResponse.ProtoReflect.Descriptor instead.
func (*PublishTunnelResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{14}
}

func (x *PublishTunnelResponse) GetPublished() []*Node {
	if x != nil {
		return x.Published
	}
	return nil
}

type UnpublishTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *UnpublishTunnelRequest) Reset() {
	*x = UnpublishTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnpublishTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishTunnelRequest) ProtoMessage() {}

func (x *UnpublishTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishTunnelRequest.ProtoReflect.Descriptor instead.
func (*UnpublishTunnelRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{15}
}

func (x *UnpublishTunnelRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type UnpublishTunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnpublishTunnelResponse) Reset() {
	*x = UnpublishTunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnpublishTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishTunnelResponse) ProtoMessage() {}

func (x *UnpublishTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishTunnelResponse.ProtoReflect.Descriptor instead.
func (*UnpublishTunnelResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{16}
}

type ReleaseTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *ReleaseTunnelRequest) Reset() {
	*x = ReleaseTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTunnelRequest) ProtoMessage() {}

func (x *ReleaseTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTunnelRequest.ProtoReflect.Descriptor instead.
func (*ReleaseTunnelRequest) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{17}
}

func (x *ReleaseTunnelRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ReleaseTunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReleaseTunnelResponse) Reset() {
	*x = ReleaseTunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseTunnelResponse) ProtoMessage() {}

func (x *ReleaseTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseTunnelResponse.ProtoReflect.Descriptor instead.
func (*ReleaseTunnelResponse) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{18}
}

type TunnelDestination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chord  *Node `protobuf:"bytes,1,opt,name=chord,proto3" json:"chord,omitempty"`
	Tunnel *Node `protobuf:"bytes,2,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
}

func (x *TunnelDestination) Reset() {
	*x = TunnelDestination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelDestination) ProtoMessage() {}

func (x *TunnelDestination) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelDestination.ProtoReflect.Descriptor instead.
func (*TunnelDestination) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{19}
}

func (x *TunnelDestination) GetChord() *Node {
	if x != nil {
		return x.Chord
	}
	return nil
}

func (x *TunnelDestination) GetTunnel() *Node {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type TunnelStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status TunnelStatusCode `protobuf:"varint,2,opt,name=status,proto3,enum=protocol.TunnelStatusCode" json:"status,omitempty"`
	Error  string           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TunnelStatus) Reset() {
	*x = TunnelStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_proto_tunnel_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStatus) ProtoMessage() {}

func (x *TunnelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_tunnel_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStatus.ProtoReflect.Descriptor instead.
func (*TunnelStatus) Descriptor() ([]byte, []int) {
	return file_spec_proto_tunnel_proto_rawDescGZIP(), []int{20}
}

func (x *TunnelStatus) GetStatus() TunnelStatusCode {
	if x != nil {
		return x.Status
	}
	return TunnelStatusCode_STATUS_OK
}

func (x *TunnelStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var file_spec_proto_tunnel_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         54242,
		Name:          "protocol.alpn_name",
		Tag:           "bytes,54242,opt,name=alpn_name",
		Filename:      "spec/proto/tunnel.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string alpn_name = 54242;
	E_AlpnName = &file_spec_proto_tunnel_proto_extTypes[0]
)

var File_spec_proto_tunnel_proto protoreflect.FileDescriptor

var file_spec_proto_tunnel_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x1a, 0x15, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x02, 0x0a,
	0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x27, 0x0a, 0x04, 0x61, 0x6c, 0x70, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c,
	0x69, 0x6e, 0x6b, 0x2e, 0x41, 0x4c, 0x50, 0x4e, 0x52, 0x04, 0x61, 0x6c, 0x70, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x22, 0xac, 0x01, 0x0a, 0x04, 0x41, 0x4c, 0x50, 0x4e, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x26, 0x0a, 0x0d, 0x53, 0x50, 0x45, 0x43,
	0x54, 0x45, 0x52, 0x5f, 0x43, 0x48, 0x4f, 0x52, 0x44, 0x10, 0x01, 0x1a, 0x13, 0x92, 0xbe, 0x1a,
	0x0f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x65, 0x72, 0x2d, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2f, 0x31,
	0x12, 0x28, 0x0a, 0x0e, 0x53, 0x50, 0x45, 0x43, 0x54, 0x45, 0x52, 0x5f, 0x43, 0x4c, 0x49, 0x45,
	0x4e, 0x54, 0x10, 0x02, 0x1a, 0x14, 0x92, 0xbe, 0x1a, 0x10, 0x73, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x72, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x31, 0x12, 0x11, 0x0a, 0x05, 0x48, 0x54,
	0x54, 0x50, 0x32, 0x10, 0x09, 0x1a, 0x06, 0x92, 0xbe, 0x1a, 0x02, 0x68, 0x32, 0x12, 0x16, 0x0a,
	0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x0a, 0x1a, 0x0c, 0x92, 0xbe, 0x1a, 0x08, 0x68, 0x74, 0x74,
	0x70, 0x2f, 0x31, 0x2e, 0x31, 0x12, 0x1a, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x0b, 0x1a, 0x11,
	0x92, 0xbe, 0x1a, 0x0d, 0x73, 0x70, 0x65, 0x63, 0x74, 0x65, 0x72, 0x2d, 0x74, 0x63, 0x70, 0x2f,
	0x31, 0x22, 0xe4, 0x01, 0x0a, 0x0b, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x3d, 0x0a, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x11, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3b, 0x0a, 0x11, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x5f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x10, 0x63, 0x68, 0x6f,
	0x72, 0x64, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a,
	0x12, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x11, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x13, 0x0a,
	0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4c, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x70, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x70, 0x65, 0x78,
	0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x18, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x70, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x70, 0x65, 0x78, 0x22, 0x11, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x18, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x48,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x1b, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x5c, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x22, 0x45, 0x0a, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x22, 0x34, 0x0a, 0x16, 0x55,
	0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32, 0x0a, 0x14,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x61, 0x0a, 0x11, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x05, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x63,
	0x68, 0x6f, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x58, 0x0a, 0x0c,
	0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x43, 0x0a, 0x10, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x10, 0x02, 0x32, 0xab, 0x05, 0x0a, 0x0d,
	0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x59, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59,
	0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x13, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x48, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a,
	0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x56, 0x0a, 0x0f, 0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x55, 0x6e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x55, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3a, 0x40, 0x0a, 0x09, 0x61, 0x6c, 0x70,
	0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe2, 0xa7, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x6c, 0x70, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x25, 0x48, 0x01, 0x5a,
	0x21, 0x6b, 0x6f, 0x6e, 0x2e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x73, 0x68, 0x2f, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spec_proto_tunnel_proto_rawDescOnce sync.Once
	file_spec_proto_tunnel_proto_rawDescData = file_spec_proto_tunnel_proto_rawDesc
)

func file_spec_proto_tunnel_proto_rawDescGZIP() []byte {
	file_spec_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_spec_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_proto_tunnel_proto_rawDescData)
	})
	return file_spec_proto_tunnel_proto_rawDescData
}

var file_spec_proto_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spec_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_spec_proto_tunnel_proto_goTypes = []interface{}{
	(TunnelStatusCode)(0),                 // 0: protocol.TunnelStatusCode
	(Link_ALPN)(0),                        // 1: protocol.Link.ALPN
	(*Link)(nil),                          // 2: protocol.Link
	(*TunnelRoute)(nil),                   // 3: protocol.TunnelRoute
	(*ClientToken)(nil),                   // 4: protocol.ClientToken
	(*ClientPingRequest)(nil),             // 5: protocol.ClientPingRequest
	(*ClientPingResponse)(nil),            // 6: protocol.ClientPingResponse
	(*RegisterIdentityRequest)(nil),       // 7: protocol.RegisterIdentityRequest
	(*RegisterIdentityResponse)(nil),      // 8: protocol.RegisterIdentityResponse
	(*GetNodesRequest)(nil),               // 9: protocol.GetNodesRequest
	(*GetNodesResponse)(nil),              // 10: protocol.GetNodesResponse
	(*GenerateHostnameRequest)(nil),       // 11: protocol.GenerateHostnameRequest
	(*GenerateHostnameResponse)(nil),      // 12: protocol.GenerateHostnameResponse
	(*RegisteredHostnamesRequest)(nil),    // 13: protocol.RegisteredHostnamesRequest
	(*RegisteredHostnamesResponse)(nil),   // 14: protocol.RegisteredHostnamesResponse
	(*PublishTunnelRequest)(nil),          // 15: protocol.PublishTunnelRequest
	(*PublishTunnelResponse)(nil),         // 16: protocol.PublishTunnelResponse
	(*UnpublishTunnelRequest)(nil),        // 17: protocol.UnpublishTunnelRequest
	(*UnpublishTunnelResponse)(nil),       // 18: protocol.UnpublishTunnelResponse
	(*ReleaseTunnelRequest)(nil),          // 19: protocol.ReleaseTunnelRequest
	(*ReleaseTunnelResponse)(nil),         // 20: protocol.ReleaseTunnelResponse
	(*TunnelDestination)(nil),             // 21: protocol.TunnelDestination
	(*TunnelStatus)(nil),                  // 22: protocol.TunnelStatus
	(*Node)(nil),                          // 23: protocol.Node
	(*descriptorpb.EnumValueOptions)(nil), // 24: google.protobuf.EnumValueOptions
}
var file_spec_proto_tunnel_proto_depIdxs = []int32{
	1,  // 0: protocol.Link.alpn:type_name -> protocol.Link.ALPN
	23, // 1: protocol.TunnelRoute.client_destination:type_name -> protocol.Node
	23, // 2: protocol.TunnelRoute.chord_destination:type_name -> protocol.Node
	23, // 3: protocol.TunnelRoute.tunnel_destination:type_name -> protocol.Node
	23, // 4: protocol.ClientPingResponse.node:type_name -> protocol.Node
	23, // 5: protocol.GetNodesResponse.nodes:type_name -> protocol.Node
	23, // 6: protocol.PublishTunnelRequest.servers:type_name -> protocol.Node
	23, // 7: protocol.PublishTunnelResponse.published:type_name -> protocol.Node
	23, // 8: protocol.TunnelDestination.chord:type_name -> protocol.Node
	23, // 9: protocol.TunnelDestination.tunnel:type_name -> protocol.Node
	0,  // 10: protocol.TunnelStatus.status:type_name -> protocol.TunnelStatusCode
	24, // 11: protocol.alpn_name:extendee -> google.protobuf.EnumValueOptions
	5,  // 12: protocol.TunnelService.Ping:input_type -> protocol.ClientPingRequest
	7,  // 13: protocol.TunnelService.RegisterIdentity:input_type -> protocol.RegisterIdentityRequest
	9,  // 14: protocol.TunnelService.GetNodes:input_type -> protocol.GetNodesRequest
	11, // 15: protocol.TunnelService.GenerateHostname:input_type -> protocol.GenerateHostnameRequest
	13, // 16: protocol.TunnelService.RegisteredHostnames:input_type -> protocol.RegisteredHostnamesRequest
	15, // 17: protocol.TunnelService.PublishTunnel:input_type -> protocol.PublishTunnelRequest
	17, // 18: protocol.TunnelService.UnpublishTunnel:input_type -> protocol.UnpublishTunnelRequest
	19, // 19: protocol.TunnelService.ReleaseTunnel:input_type -> protocol.ReleaseTunnelRequest
	6,  // 20: protocol.TunnelService.Ping:output_type -> protocol.ClientPingResponse
	8,  // 21: protocol.TunnelService.RegisterIdentity:output_type -> protocol.RegisterIdentityResponse
	10, // 22: protocol.TunnelService.GetNodes:output_type -> protocol.GetNodesResponse
	12, // 23: protocol.TunnelService.GenerateHostname:output_type -> protocol.GenerateHostnameResponse
	14, // 24: protocol.TunnelService.RegisteredHostnames:output_type -> protocol.RegisteredHostnamesResponse
	16, // 25: protocol.TunnelService.PublishTunnel:output_type -> protocol.PublishTunnelResponse
	18, // 26: protocol.TunnelService.UnpublishTunnel:output_type -> protocol.UnpublishTunnelResponse
	20, // 27: protocol.TunnelService.ReleaseTunnel:output_type -> protocol.ReleaseTunnelResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	11, // [11:12] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_spec_proto_tunnel_proto_init() }
func file_spec_proto_tunnel_proto_init() {
	if File_spec_proto_tunnel_proto != nil {
		return
	}
	file_spec_proto_node_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_spec_proto_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateHostnameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateHostnameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredHostnamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredHostnamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishTunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnpublishTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnpublishTunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseTunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelDestination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_proto_tunnel_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_proto_tunnel_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 1,
			NumServices:   1,
		},
		GoTypes:           file_spec_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_spec_proto_tunnel_proto_depIdxs,
		EnumInfos:         file_spec_proto_tunnel_proto_enumTypes,
		MessageInfos:      file_spec_proto_tunnel_proto_msgTypes,
		ExtensionInfos:    file_spec_proto_tunnel_proto_extTypes,
	}.Build()
	File_spec_proto_tunnel_proto = out.File
	file_spec_proto_tunnel_proto_rawDesc = nil
	file_spec_proto_tunnel_proto_goTypes = nil
	file_spec_proto_tunnel_proto_depIdxs = nil
}
