// Code generated by "stringer -type=direction -linecomment"; DO NOT EDIT.

package overlay

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[directionIncoming-0]
	_ = x[directionOutgoing-1]
}

const _direction_name = "IncomingOutgoing"

var _direction_index = [...]uint8{0, 8, 16}

func (i direction) String() string {
	if i < 0 || i >= direction(len(_direction_index)-1) {
		return "direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _direction_name[_direction_index[i]:_direction_index[i+1]]
}
