name: Pipeline
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "Jenkinsfile"

jobs:
  testing:
    name: Short Tests with Race Detector
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        go: ["1.24.1"]
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Build UI
        run: make ui
      - name: Quick Test with Race Detector
        run: go test -v -short -race -timeout 120s ./...
  integration:
    name: Run Integration Tests
    runs-on: "ubuntu-latest"
    services:
      dind:
        image: docker:23.0.6-dind-rootless
        ports:
          - 2375:2375
    needs: [testing]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
      - name: Build UI
        run: make ui
      - name: Run Integration Tests with Race Detector
        run: make integration_test
  full:
    name: Run Full Test Suite
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:28.0.1-dind-rootless
        ports:
          - 2375:2375
    needs: [testing, integration]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"
          cache-dependency-path: tun/client/ui/package-lock.json
      - name: Build UI
        run: make ui
      - name: Test short, long, extended, and concurrency validation
        run: make full_test TIMEOUT=600s
  rolling:
    name: Rolling release
    runs-on: ubuntu-latest
    needs: [testing, integration]
    permissions:
      contents: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"
          cache-dependency-path: tun/client/ui/package-lock.json
      - name: Build UI
        run: make ui
      - name: Build release binaries with WAL helper
        run: make -j$(nproc) release wal=1
      - name: Build compatability binaries
        run: make -j$(nproc) compat
      - name: Rolling release on main
        uses: softprops/action-gh-release@v1
        with:
          name: "Automatic Build on main branch"
          body: "This is a rolling release with the latest build artifacts on main branch. The release is updated every time commit(s) is pushed to main."
          prerelease: true
          tag_name: edge
          files: bin/**
